// Generated by 'unplugin-auto-import'
export {}
declare global {
  const Footer: typeof import('./src/components/Footer.jsx')['default']
  const Header: typeof import('./src/components/Header.jsx')['default']
}
